name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Hello World"
      - name: Dime la fecha
        run: date
      - name: comandito
        run: ls -l